### ISSUE TITLE
Username Whitespace

### ISSUE THREAD

**Issue by Xiaoyu-Ben-Wang** [CMPUT301W21T12/FAANG-GANG#84]
What is wrong:
* Users can insert whitespace into username upon account creation.
* This is successfully uploaded to firebase

Expected behaviour:
* Instead, the application should alert user's that the username is invalid.

**Comment by Shao-Zhang** [comment]
Fixed in 
commit 7813368b001bb19b8a5a125e873ad9fb53930c1f
